### ISSUE TITLE
hey this build doesn't work on fedora silverblue

### ISSUE THREAD

**Issue by tazihad** [ivan-hc/MPV-appimage#1]
```
./MPV-Media-Player-0.35.0-x86_64.AppImage
sed: /tmp/.mount_qBittoU2lfZr/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by sed)
mpv: error while loading shared libraries: libavdevice.so.59: cannot open shared object file: No such file or directory
```

**Comment by ivan-hc** [comment]
this seems to be not a problem of MPV but there is something wrong in your ffmpeg installation

https://www.google.com/search?client=firefox-b-d&q=error+while+loading+shared+libraries%3A+libavdevice.so.59%3A+cannot+open+shared+object+file%3A+No+such+file+or+directory

**Comment by ivan-hc** [comment]
This is just a little tip to show you how to investigate by yourself

https://user-images.githubusercontent.com/88724353/196041913-4ead79ef-0b46-4251-b441-952d00ef4294.mp4

in

    export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"

the first path, ie `/lib/x86_64-linux-gnu/` uses the libraries available on the host (in my case, I use Debian), while all the other paths starting with `:"${HERE}"` are using the libraries inside the AppImage

as you can see, the AppRun is a simple bash scriptyou have nothing to do but editing the file the way you like it to made it work on your system

Let me know if you find something, I'll correct this too

**Comment by tazihad** [comment]
@ivan-hc Fedora silverblue doesn't come with ffmpeg. is this the reason?

**Comment by ivan-hc** [comment]
> @ivan-hc Fedora silverblue doesn't come with ffmpeg. is this the reason?

I don't know if ffmpeg is already available on Fedora out of the box, try to install it from your package manager

**Comment by tazihad** [comment]
@ivan-hc shouldn't this come included with appimage?

**Comment by ivan-hc** [comment]
> @ivan-hc shouldn't this come included with appimage?

Theoretically yes, but sometimes the package can be built with fewer dependencies to make the AppImage smaller and ffmpeg is something many multimedia programs use on the host. At least that's what I have to do when an AppRun requires some extra variables that excape me.

EDIT: just updated the recipe into the main script of this repository to include ffmpeg too. Download the AppImage again 

https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous

Please close this issue if the app works for you

**Comment by tazihad** [comment]
still not working.
```
sed: /tmp/.mount_MPV-Me7ztoy1/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by sed)
mpv: error while loading shared libraries: libavdevice.so.59: cannot open shared object file: No such file or directory

```

**Comment by ivan-hc** [comment]
What if you replace

    export LD_PRELOAD="${HERE}/libunionpreload.so"
with

    export LD_PRELOAD="${HERE}/libunionpreload.so":/usr/lib/x86_64-linux-gnu/libavdevice.so.59

?

**Comment by ivan-hc** [comment]
hi, I think that this time it should work well, also without ffmpeg installed

https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous

just tested on Debian and Arch Linux, this is based on Ubuntu 18.04 so it should work on any GNU/Linux distro.

I think the issue was due to the different `LD_LIBRARY_PATH` for the video drivers between the Debian-based distributions (usually in `/usr/lib/x86_64-linux-gnu/dri/`) and other systems (Arch Linux has these libraries directly in `/usr/lib/dri/`, maybe this is the same for Fedora and other distributions).

Let me know if this works for you now.

Usage:

    ./*.AppImage your-video.mp4

To have a GUI, use the command:

     ./*.AppImage --player-operation-mode=pseudo-gui --
To have a launcher in your menu, use "AM" or "AppMan", more details on https://github.com/ivan-hc

**Comment by ivan-hc** [comment]
Try this new release, is based on JuNest (Arch Linux-based distro that works as guest on any distro) and includes all libraries it needs: https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous
