### ISSUE TITLE
`/lib64/libncursesw.so.6: version `NCURSESW6_5.X.XXXXXXXX' not found` on openSUSE Leap 15.6

### ISSUE THREAD

**Issue by Chirunos** [ivan-hc/MPV-appimage#14]
MPV-Media-Player_0.35.1-4_GLIBC-2.36-9_x86-64.AppImage
Linux 6.4

Full terminal output:
```
/tmp/.mount_MPV-MeapqrGN/usr/bin/mpv: /lib64/libncursesw.so.6: version `NCURSESW6_5.3.20021019' not found (required by /tmp/.mount_MPV-MeapqrGN/usr/lib/x86_64-linux-gnu/libcaca.so.0)
/tmp/.mount_MPV-MeapqrGN/usr/bin/mpv: /lib64/libncursesw.so.6: version `NCURSESW6_5.1.20000708' not found (required by /tmp/.mount_MPV-MeapqrGN/usr/lib/x86_64-linux-gnu/libcaca.so.0)
```

I have `libcaca0`, `libncurses5`, `libncurses5-32bit`, `libncurses6` and `libncurses6-32bit` installed. This does not happen with the current continuous build (MPV-Media-Player_0.38.0-6-vm-archimage3.4-x86_64.AppImage).

**Comment by ivan-hc** [comment]
The old ones are based on .deb packages and can see system libraries

The Archimage is an Arch Linux container into an AppImage, so it uses its own libraries.

I suggest to rely on the more recent one, the Archimage, that works also on systems that have not libfuse2
