### ISSUE TITLE
why mpv can't run video from `/run/media/username/USB/file.mp4`

### ISSUE THREAD

**Issue by candrapersada** [ivan-hc/MPV-appimage#15]

**Comment by ivan-hc** [comment]
Because /run/media is not mounted through bubblewrap

This is an Archimage, an Arch Linux container into an AppImage, so it  only mounts the most common directories on host from guest. `/run/media` is not listed, while `/run/user` yes.

I'll try to fix this ASAP

**Comment by ivan-hc** [comment]
try now

**Comment by candrapersada** [comment]
and how to update Continuous build from am/appman?

**Comment by ivan-hc** [comment]
`am -u` or `am -u --apps` or `am -u mpv`

`appman -u` or `appman -u --apps` or `appman -u mpv`

**Comment by Samueru-sama** [comment]
@candrapersada Give a try to my mpv appimage if you want, which is option 1 when you do `appman -i mpv`

**Comment by ivan-hc** [comment]
as @Samueru-sama says, there is also another one, at https://github.com/Samueru-sama/mpv-AppImage, if you run `appman -i mpv`, select the number 1, the number 2 is the one available on this repo.
