### ISSUE TITLE
/tmp/.mount_MPV-Me5R4Lki/usr/bin/mpv: error while loading shared libraries: liblapack.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/MPV-appimage#5]
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/95d49fd9-3754-4514-8858-03da2ad8e8e4)

**Comment by ivan-hc** [comment]
The appimage works well for me, I can't reproduce that. Maybe you should install some dependences on your host system. This AppImage also uses dependences from the host. If it does not work, try with an onder version from this list:

https://github.com/ivan-hc/MPV-appimage/releases/tag/stable-releases

They are built from three different brances of Debian, so they work for different GLIBC versions. All depend on your distribution.

**Comment by ivan-hc** [comment]
Replaced the version built from Debian with the version based on Arch Linux (JuNest) https://github.com/ivan-hc/MPV-appimage/commit/d1423bca7dafcabe5fb75df0201f1a18db188d56
