### ISSUE TITLE
/tmp/.mount_MPV-MeWQP6Zj/usr/bin/mpv: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/MPV-appimage#6]
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/7abddfce-8619-4c68-a14e-eec3614760d1)

**Comment by ivan-hc** [comment]
duplicate https://github.com/ivan-hc/MPV-appimage/issues/6
