### ISSUE TITLE
you new version ,I cannot run, and play

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/MPV-appimage#8]

**Comment by ivan-hc** [comment]
it works for me, before you open an issue you should copy/paste the log, so I can investigate on the bug.

The next time you post an issue, run the AppImage from the Terminal and let me know what doesn't work.

I can't be in your mind to know what does not work for you.

**Comment by ivan-hc** [comment]
Fix https://github.com/ivan-hc/MPV-appimage/commit/b49b7267fd78780ae64d82e9254c23425cde5bbd

Wait the time Github Ations have finished, just loading now

**Comment by ivan-hc** [comment]
UPDATE, now the new release is able to read also URLs  https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous

PS: Thanks for your concern, without your feedback I wouldn't have been interested in the AppImage, which was broken. I usually assemble them on my PC and then send the recipe to GH Actions, unaware if some parameter will make the app work or not.
