### ISSUE TITLE
Streaming issues

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/MPV-appimage#9]
Trying to investigate about the reason because the same AppImage, built on GH Actions and on the PC gives different results

# TESTS

### AppImage downloaded from here (the video does not work):

    [ffmpeg] tcp: Failed to resolve hostname www.youtube.com: Temporary failure in name resolution
    Failed to open https://www.youtube.com/watch?v=71XXo28ARF4.
    [ytdl_hook] ERROR: [youtube] 71XXo28ARF4: Unable to download API page: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'))) 
    [ytdl_hook] youtube-dl failed: unexpected error occurred 
    
    Exiting... (Errors when loading file)

### The same AppImage, but built on my PC (the video works):

     (+) Video --vid=1 (*) (vp9 3840x2160 25.000fps)
     (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
         Subs  --sid=1 --slang=live_chat 'json' (null) (external)
    File tags:
     Uploader: Breaking Italy
     Channel_URL: https://www.youtube.com/channel/UC4V3oCikXeSqYQr0hBMARwg
    [vo/gpu/x11] XOpenIM() failed. Unicode input will not work.
    [vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
    [vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
    [vo/gpu/opengl] No primary DRM device could be picked!
    [vo/gpu/opengl] Failed to find a usable DRM primary node!
    [vo/gpu/opengl] Failed to create KMS.
    [vo/gpu-next/x11] XOpenIM() failed. Unicode input will not work.
    [vo/gpu-next] Can't handle VT release - signal already used
    [vo/gpu-next/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
    [vo/gpu-next/opengl] No primary DRM device could be picked!
    [vo/gpu-next/opengl] Failed to find a usable DRM primary node!
    [vo/gpu-next/opengl] Failed to create KMS.
    [vo/vdpau/x11] XOpenIM() failed. Unicode input will not work.
    Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
    [vo/vdpau] Error when calling vdp_device_create_x11: 1
    [vo/xv/x11] XOpenIM() failed. Unicode input will not work.
    [vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
    [E] pw.loop [loop.c:67 pw_loop_new()] 0x500000511ff0: can't make support.system handle: No such file or directory
    AO: [pulse] 48000Hz stereo 2ch float
    VO: [xv] 3840x2160 yuv420p
    AV: 00:00:00 / 02:21:26 (0%) A-V:  0.000 Cache: 1.2s/1MB
    [osd/libass] fontselect: failed to find any fallback with glyph 0x0 for font: (sans-serif, 400, 0)
    AV: 00:00:02 / 02:21:26 (0%) A-V:  0.000 Cache: 3.4s/2MB
    
    Exiting... (Quit)

This is really strange!

**Comment by newyorkthink** [comment]
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/e949bb5e-8fbc-4f65-96c8-e6cacaba19e7)

i work ,thank you, i can play offline video

**Comment by ivan-hc** [comment]
Glad to hear that it works at least for the purpose you see fit. Unfortunately, this bug results in the lack of an online streaming feature that is very important to most MPV users. :(

**Comment by ivan-hc** [comment]
New AppRun

    #!/bin/sh
    APP=mpv
    HERE="$(dirname "$(readlink -f $0)")"
    export UNION_PRELOAD=$HERE
    export JUNEST_HOME=$HERE/.junest
    export PATH=$HERE/.local/share/junest/bin/:$PATH
    mkdir -p $HOME/.cache
    $HERE/.local/share/junest/bin/junest proot -n -b "--bind=/home --bind=/home/$(echo $USER) --bind=/media --bind=/opt --bind=/etc" -- $APP "$@"

Mounting /etc solves the issue!
